spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UserSecurityDb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    time-zone: UTC
  sql:
    init:
      mode: always

app:
  jwtSecret: secret
  jwtExpirationInMs: 3600000

server:
  port: 8083


